language: perl
sudo: false

compiler:
  - clang
  - gcc

perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"

install:
  # Deal with dependencies
  - cpanm --installdeps --verbose .
  - cpanm -n Devel::Cover
  - cpanm -n Devel::Cover::Report::Coveralls
script:
  - perl Makefile.PL --profiling --sassc
  - make -j5
  - HARNESS_PERL_SWITCHES=-MDevel::Cover PSASS_FORCE_PLUGIN_CHECK=1 make test
  - make install
  - echo "query psass version"
  - psass --version
  - echo "list of all plugins"
  - psass --list-plugins
  - echo "query sassc version"
  - sassc --version
after_success:
  - find -name *.gcda -type f -exec gcov-4.8 -abc -o `basename {}` {} \;
  - cover -gcov -report coveralls -ignore_re "^/usr" -ignore_re "^plugins" -ignore_re "^libsass"
